### ISSUE TITLE
 can also be activated on the pages of the groups?

### ISSUE THREAD

**Issue by 00BbnN00** [kvnxiao/mangadex-tama#33]
hello, thanks for the nice app.
would it be possible to make it work also on group pages?

like for example:

https://mangadex.org/group/657/no-group
https://mangadex.org/group/14/lhtranslation
https://mangadex.org/group/7914/not-a-scans-scans-group
.... etc.
https://mangadex.org/group/**/**"

**Comment by kvnxiao** [comment]
Done for 0.2.0, sorry it took so long I didn't notice this issue on GitHub.
Waiting for Chrome Extensions to review and release the updated package.

**Comment by kvnxiao** [comment]
@00BbnN00 Chrome has reviewed and updated the extension to 0.2.0
